name: Build AppImage
on:
  workflow_dispatch:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - "main"

jobs:
  version:
    name: Dbeaver CE AppImage Version
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      create: ${{ steps.check.outputs.create }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Check version
        id: check
        run: |
          bash version.sh
  build:
    name: DBeaver CE AppImage Build
    needs: version
    if: ${{ needs.version.outputs.create == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build DBeaver CE
        run: |
          bash build.sh
          echo "$DBEAVER_CE_VERSION"
      - name: Upload artifact
        if: ${{ steps.check_tag.outputs.exists }} == "false"
        uses: actions/upload-artifact@v1
        with:
          name: dbeaver-ce.AppImage
          path: 'dist'
      - name: Release
        if: ${{ !steps.check_tag.outputs.exists }} == "false"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: DBeaver CE AppImage ${{ env.DBEAVER_CE_VERSION }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            dist/
          repo_token: ${{ secrets.GITHUB_TOKEN }}
