name: Build AppImage
on:
  workflow_dispatch:
  schedule:
    - cron: "5 */12 * * *"
  push:
    branches:
      - "main"

jobs:
  build:
    name: Dbeaver CE AppImage
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Check version
        id: build
        run: |
          wget https://raw.githubusercontent.com/valicm/appimage-bash/main/build.sh
          chmod +x build.sh
          bash build.sh verify
      - name: Upload artifact
        if: ${{ env.APP_UPDATE_NEEDED == 1 }}
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.APP_SHORT_NAME }}.AppImage
          path: 'dist'
      - name: Release
        if: ${{ env.APP_UPDATE_NEEDED == 1 }}
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ${{ env.APP_NAME }} AppImage ${{ env.APP_VERSION }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            dist/
          repo_token: ${{ secrets.GITHUB_TOKEN }}
